name: WebAssembly BigQuery CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Permet de déclencher le workflow manuellement

jobs:
  build-and-generate-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Compile Rust to WebAssembly
        run: |
          chmod +x ./scripts/compile_wasm.sh
          ./scripts/compile_wasm.sh

      - name: Generate BigQuery SQL
        run: |
          chmod +x ./scripts/generate_bq_query.sh
          ./scripts/generate_bq_query.sh

      - name: Create ZIP archive of artifacts
        run: |
          cd artifacts
          zip -r ../wasm-bigquery-artifacts.zip .
          cd ..
          echo "Taille de l'archive ZIP: $(du -h wasm-bigquery-artifacts.zip)"

      - name: Upload artifacts folder
        uses: actions/upload-artifact@v3
        with:
          name: wasm-bigquery-artifacts
          path: artifacts/
          retention-days: 90

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v3
        with:
          name: wasm-bigquery-artifacts-zip
          path: wasm-bigquery-artifacts.zip
          retention-days: 90

      # Création d'une release pour les pushes sur main
      - name: Create Release
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: WebAssembly BigQuery Release ${{ github.run_number }}
          tag_name: v0.1.${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            wasm-bigquery-artifacts.zip
            artifacts/bq_query.sql
          body: |
            ## WebAssembly BigQuery Release
            
            Cette release contient:
            - Fichier WASM compilé
            - Requête SQL prête à l'emploi pour BigQuery
            - Autres artifacts du build
            
            Généré automatiquement par GitHub Actions le ${{ github.event.repository.updated_at }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
