name: WebAssembly BigQuery CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y binaryen xxd

      - name: Compile Rust to WebAssembly
        run: |
          chmod +x ./scripts/compile_wasm.sh
          ./scripts/compile_wasm.sh

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate BigQuery SQL using Python
        run: |
          chmod +x ./scripts/generate_sql.py
          python ./scripts/generate_sql.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bigquery-wasm-function
          path: artifacts/

      - name: Create release ZIP
        if: github.ref == 'refs/heads/main'
        run: |
          cd artifacts
          zip -r ../bigquery-wasm-function.zip *

      - name: Create GitHub Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: bigquery-wasm-function.zip
          name: WebAssembly BigQuery Function v${{ github.run_number }}
          tag_name: v${{ github.run_number }}
          body: |
            # WebAssembly BigQuery Function Release
            
            This release contains a SQL file that creates a BigQuery UDF powered by WebAssembly.
            
            ## Changes in this version
            
            - Built from commit: ${{ github.sha }}
            - Build number: ${{ github.run_number }}
            
            ## Installation
            
            1. Download the ZIP file
            2. Extract the SQL file
            3. Run in BigQuery console
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
